#!/usr/bin/env python3
"""Generate a cross-language AuxPoW fixture for auxpow_crosscheck_test.go.

Production AuxPoW (v2): mines a witness on CPU, generates a REAL Pearl v2 plonky2
proof, and builds AuxPowData with the pool's REAL construction
(modelos_pool.auxpow_build._build_pool_auxpow_hex). The Go test feeds the bytes into
the node's real VerifyAuxPow, so the Python construction and Go verification (108-byte
header, cert proof_commitment binding, σ_modelos coinbase commitment, merkle binding,
real plonky2 verification) can't silently drift.

Run with the v2 wheel venv from repo root:
    /tmp/v2venv/bin/python node/blockchain/testdata/gen_auxpow_fixture.py
"""
import json
import os
import sys

import pearl_mining as pm

_REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, os.path.join(_REPO, "miner", "modelos-pool", "src"))
from modelos_pool.auxpow_build import _build_pool_auxpow_hex, _pearl_header_prefix  # noqa: E402

# Easy nbits so the witness is found in well under a second. VerifyAuxPow grades the
# real jackpot against this (the child/MDL target), so the header is mined at it too.
MODELOS_BITS = 0x1D2FFFFF
MODELOS_HEIGHT = 10_001          # > auxPowActivationHeight (10_000)
PREV_MDL = "aa" * 32             # MDL block prevBlock (display/BE); σ_modelos is its LE
PREV_PRL = "bb" * 32
# Deterministic prl1 P2TR address (witness v1 + 32-byte program 0x00..0x1f). The
# Pearl coinbase pays its subsidy here; VerifyAuxPow ignores the output, so any
# valid bech32m P2TR works — it just must decode (the builders require pool_address).
PEARL_POOL_ADDR = "prl1pqqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0ss8729k"


class _Tmpl:
    def __init__(self):
        self.modelos_template = {"previousblockhash": PREV_MDL}
        self.pearl_template = {
            "height": 7, "version": 0, "previousblockhash": PREV_PRL,
            "curtime": 0x66666666, "bits": f"{MODELOS_BITS:08x}",
        }


def main():
    tmpl = _Tmpl()
    sigma_modelos = bytes.fromhex(PREV_MDL)[::-1]

    # Per-session extranonce: exercises the unique-work path (each miner's Pearl coinbase
    # is unique → unique Pearl header). The mined header AND the AuxPowData must use the
    # SAME extranonce so the Pearl coinbase the proof commits to matches the one in AuxPowData.
    extra_nonce = bytes.fromhex("0000002a")

    # Build the EXACT header the pool will mine: prefix's merkle_root commits to the
    # coinbase that embeds MDL* + σ_modelos + extranonce. Mine + prove against that header.
    prefix = _pearl_header_prefix(
        tmpl.pearl_template, sigma_modelos, PEARL_POOL_ADDR, extra_nonce)
    hdr = pm.IncompleteBlockHeader.from_bytes(prefix)
    cfg = pm.MiningConfiguration(
        common_dim=1024, rank=32, mma_type=pm.MMAType.Int7xInt7ToInt32,
        rows_pattern=pm.PeriodicPattern.from_list([0, 8, 64, 72]),
        cols_pattern=pm.PeriodicPattern.from_list([0, 1, 8, 9, 32, 33, 40, 41]),
        moe=None,
    )
    pp = pm.mine(256, 128, 1024, hdr, cfg)
    zk = pm.generate_proof_v2(hdr, pp)

    auxpow_hex = _build_pool_auxpow_hex(
        tmpl, bytes(zk.public_data), bytes(zk.proof_data), PEARL_POOL_ADDR, extra_nonce)

    fixture = {
        "_comment": "Generated by gen_auxpow_fixture.py — AuxPowData from the pool's "
                    "auxpow_build with a REAL Pearl v2 ZK proof. Consumed by "
                    "auxpow_crosscheck_test.go against the real VerifyAuxPow.",
        "auxpow_hex": auxpow_hex,
        "modelos_height": MODELOS_HEIGHT,
        "modelos_state_hash_hex": sigma_modelos.hex(),
        "modelos_bits": f"{MODELOS_BITS:08x}",
    }
    out = os.path.join(os.path.dirname(__file__), "auxpow_verify_fixture.json")
    with open(out, "w") as f:
        json.dump(fixture, f, indent=2)
    print(f"wrote {out}  (auxpow {len(auxpow_hex)//2} bytes, "
          f"proof {len(zk.proof_data)}B, public {len(zk.public_data)}B)")


if __name__ == "__main__":
    main()
